Suppose, a fruit-seller sold 20 mangoes and 10 oranges in one day for a total of . The next day he sold 17 mangoes and 22 oranges for . If the prices of the fruits remained unchanged on both the days, what was the price of one mango and one orange?

In [154]:
import numpy as np
A = np.array([[20, 10],
              [17, 22]], dtype=np.float64)
b = np.array([350, 500], dtype=np.float64)
x = np.linalg.solve(A, b)

print("Mango Price",x[0])
print("Orange Price",x[1])

Mango Price 10.000000000000002
Orange Price 14.999999999999996


1. Using Numpy to invert the matrices:

In [155]:
import numpy as np

def inv_of_matrix(matrix):
    try:
        det = np.linalg.det(matrix)
        if det != 0:
            inv_matrix = np.linalg.inv(matrix)
            return inv_matrix
        else:
            return None  
    except np.linalg.LinAlgError:
        return None
    
A = np.array([[3, -7, 45, 21],
              [12, 11, 10, 17],
              [6, 25, -80, -24],
              [17, 55, -9, 7]], dtype=np.dtype(float))

B = np.array([[1, 1, 1, 1],
              [1, 2, 2, 2],
              [2, 3, 4, 4],
              [4, 5, 6, 7]], dtype=np.dtype(float))        

print(inv_of_matrix(A))
print(inv_of_matrix(B))

[[-2.73050828e+00  1.48528059e+00 -1.34659614e+00 -3.24862006e-02]
 [ 4.82405704e-01 -2.78748850e-01  2.33210672e-01  2.93238270e-02]
 [-6.54036339e-01  3.24287029e-01 -3.40616375e-01  6.72723091e-03]
 [ 2.00000000e+00 -1.00000000e+00  1.00000000e+00 -1.11022302e-16]]
[[ 2.00000000e+00 -1.00000000e+00 -8.88178420e-16  3.33066907e-16]
 [-4.44089210e-16  2.00000000e+00 -1.00000000e+00  4.44089210e-16]
 [ 1.00000000e+00 -1.00000000e+00  2.00000000e+00 -1.00000000e+00]
 [-2.00000000e+00 -0.00000000e+00 -1.00000000e+00  1.00000000e+00]]


2. Solve the following equations with the 3 methods in our class:

In [156]:
import numpy as np

# Step 1
# Construct matrix and vector corresponding to the system of linear equations
# AX = B

A = np.array([[12, -2, 3, 1],
              [-2, 15, 6, -3],
              [1, 6, 20, -4],
              [0, -3, 2, 9]], dtype=np.dtype(float))

b = np.array([0, 0, 20, 0], dtype=np.dtype(float))

In [157]:
A

array([[12., -2.,  3.,  1.],
       [-2., 15.,  6., -3.],
       [ 1.,  6., 20., -4.],
       [ 0., -3.,  2.,  9.]])

In [158]:
b

array([ 0.,  0., 20.,  0.])

In [159]:
# Step 2

d = np.linalg.det(A)
d

26914.000000000025

In [160]:
# Solution 1: Using the inv() and dot() Methods

inv_A = np.linalg.inv(A)
print(inv_A)

[[ 0.08738946  0.01597682 -0.01671992 -0.01181541]
 [ 0.01619975  0.08289366 -0.02860965  0.01311585]
 [-0.00780263 -0.01928364  0.05506428  0.01891209]
 [ 0.00713383  0.03191647 -0.02177305  0.11128037]]


In [161]:
X = np.linalg.inv(A).dot(b)
print(X)

[-0.33439845 -0.57219291  1.10128558 -0.4354611 ]


In [162]:
# Solution 2: Using the solve() Method

x = np.linalg.solve(A,b)

print(f"Determinant of matrix A: {d}")
print(f"Solution vector: {x}")

Determinant of matrix A: 26914.000000000025
Solution vector: [-0.33439845 -0.57219291  1.10128558 -0.4354611 ]


In [224]:
# Solution 3: Solve the System of Equations by Elementary Operations and Row Reduction

def MultiplyRow(M, row_num, row_num_multiple):
    # .copy() function is required here to keep the original matrix without any changes
    M_new = M.copy()     
    # exchange row_num of the matrix M_new with its multiple by row_num_multiple
    # Note: for simplicity, you can drop check if  row_num_multiple has non-zero value, which makes the operation valid
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new
    
def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()     
    # multiply row_num_1 by row_num_1_multiple and add it to the row_num_2, 
    # exchanging row_num_2 of the matrix M_new with the result
    M_new[row_num_2] += M_new[row_num_1] * row_num_1_multiple
    return M_new

def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()     
    # exchange row_num_1 and row_num_2 of the matrix M_new
    M_new[row_num_1] = M_new[row_num_1] + M_new[row_num_2]
    M_new[row_num_2] = M_new[row_num_1] - M_new[row_num_2]
    M_new[row_num_1] = M_new[row_num_1] - M_new[row_num_2]
    return M_new

In [225]:
A_augmented = np.array([[12, -2, 3, 1],
                        [-2, 15, 6, -3],
                        [1, 6, 20, -4],
                        [0, -3, 2, 9]], dtype=float)

print("Original matrix:")
print(A_augmented)

# R1 --> R1 + 6R2
A_augmented = AddRows(A_augmented, 1, 0, 6)

# R2 --> R2 + 2R3
A_augmented = AddRows(A_augmented, 2, 1, 2)

# R3 --> R3 + 2R4
A_augmented = AddRows(A_augmented, 3, 2, 2)

# R4 --> R4/3
A_augmented = MultiplyRow(A_augmented, 3, 1/3)

print(A_augmented)

Original matrix:
[[12. -2.  3.  1.]
 [-2. 15.  6. -3.]
 [ 1.  6. 20. -4.]
 [ 0. -3.  2.  9.]]
[[  0.          88.          39.         -17.        ]
 [  0.          27.          46.         -11.        ]
 [  1.           0.          24.          14.        ]
 [  0.          -1.           0.66666667   3.        ]]


In [226]:
# Swap R1 and R3
A_augmented = SwapRows(A_augmented, 0, 2)
A_augmented

array([[  1.        ,   0.        ,  24.        ,  14.        ],
       [  0.        ,  27.        ,  46.        , -11.        ],
       [  0.        ,  88.        ,  39.        , -17.        ],
       [  0.        ,  -1.        ,   0.66666667,   3.        ]])

In [227]:
# Swap R2 and R4
A_augmented = SwapRows(A_augmented, 1, 3)
A_augmented

array([[  1.        ,   0.        ,  24.        ,  14.        ],
       [  0.        ,  -1.        ,   0.66666667,   3.        ],
       [  0.        ,  88.        ,  39.        , -17.        ],
       [  0.        ,  27.        ,  46.        , -11.        ]])

In [228]:
# R3 --> R3 + 88R2
A_augmented = AddRows(A_augmented, 1, 2, 88)

# R4 --> R4 + 27R2
A_augmented = AddRows(A_augmented, 1, 3, 27)
A_augmented

array([[  1.        ,   0.        ,  24.        ,  14.        ],
       [  0.        ,  -1.        ,   0.66666667,   3.        ],
       [  0.        ,   0.        ,  97.66666667, 247.        ],
       [  0.        ,   0.        ,  64.        ,  70.        ]])

In [229]:
# R4 --> R4/64
A_augmented = MultiplyRow(A_augmented, 3, 1/64)

# R3 --> R3/247
A_augmented = MultiplyRow(A_augmented, 2, 1/247)
A_augmented

array([[ 1.        ,  0.        , 24.        , 14.        ],
       [ 0.        , -1.        ,  0.66666667,  3.        ],
       [ 0.        ,  0.        ,  0.39541161,  1.        ],
       [ 0.        ,  0.        ,  1.        ,  1.09375   ]])

In [231]:
A_augmented = MultiplyRow(A_augmented, 3, 1/1.09375)
A_augmented

array([[ 1.        ,  0.        , 24.        , 14.        ],
       [ 0.        , -1.        ,  0.66666667,  3.        ],
       [ 0.        ,  0.        ,  0.39541161,  1.        ],
       [ 0.        ,  0.        ,  0.91428571,  1.        ]])

In [232]:
# R2 --> R2 - 3R3
A_augmented = AddRows(A_augmented, 2, 1, -3)

# R3 --> R3 - R4
A_augmented = AddRows(A_augmented, 3, 2, -1)
A_augmented

array([[ 1.        ,  0.        , 24.        , 14.        ],
       [ 0.        , -1.        , -0.51956815,  0.        ],
       [ 0.        ,  0.        , -0.51887411,  0.        ],
       [ 0.        ,  0.        ,  0.91428571,  1.        ]])

In [237]:
A_matrix = np.array([[ 1.        ,  0.        , 24.        , 14.        ],
       [ 0.        , -1.        , -0.51956815,  0.        ],
       [ 0.        ,  0.        , -0.51887411,  0.        ],
       [ 0.        ,  0.        ,  0.91428571,  1.        ]], dtype=float)


b_matrix = np.array([0, 0, 20, 0], dtype=float)

In [238]:
# Coefficient matrix A
A_matrix = np.array([[1.0, 0.0, 24.0, 14.0],
                     [0.0, -1.0, -0.51956815, 0.0],
                     [0.0, 0.0, -0.51887411, 0.0],
                     [0.0, 0.0, 0.91428571, 1.0]], dtype=float)

# Right-hand side vector b
b_matrix = np.array([0.0, 0.0, 20.0, 0.0], dtype=float)

# Solve for X using numpy.linalg.solve
X = np.linalg.solve(A_matrix, b_matrix)

# Print the solution
print("Solution:")
print(X)


Solution:
[431.70394684  20.02675177 -38.54499505  35.24113816]


In [239]:
# Augmented matrix [A_matrix | b_matrix]
augmented_matrix = np.array([[1.0, 0.0, 24.0, 14.0, 0.0],
                              [0.0, -1.0, -0.51956815, 0.0, 0.0],
                              [0.0, 0.0, -0.51887411, 0.0, 20.0],
                              [0.0, 0.0, 0.91428571, 1.0, 0.0]], dtype=float)

num_rows, num_cols = augmented_matrix.shape

for col in range(num_cols - 2):
    for row in range(col + 1, num_rows):
        factor = augmented_matrix[row][col] / augmented_matrix[col][col]
        augmented_matrix[row] -= factor * augmented_matrix[col]

# Back-substitution
variables = np.zeros(num_cols - 1)

for row in range(num_rows - 1, -1, -1):
    variables[row] = (augmented_matrix[row][-1] - np.dot(augmented_matrix[row][row + 1:num_cols - 1], variables[row + 1:num_cols - 1])) / augmented_matrix[row][row]

# Print the solution
print("Solution:")
print(variables)


Solution:
[431.70394684  20.02675177 -38.54499505  35.24113816]


In [240]:
# while i have worked on notes, it has almost equal results but i have tried with different method 

x1 = 8.92
x2 = 1.32
x3 = 0.275
x4 = 0.320

There is an huge different in solutions, i have shared photos too

3. Write a function calc_similarity(s1,s2) where s1 and s2 are strings (may have different size). From s1 and s2, the function should construct two vectors, v1 and v2, where v1[0] is the number of a’s in s1, v1[1] is the number b’s in s1, and so on until v1[25], which is the number of z’s in v1. The vector v2 should be similarly constructed from s2. The output should be cos(θ).

In [171]:
import numpy as np
from collections import Counter

def construct_letter_frequency_vector(s):
    # Initialize a vector of zeros for all 26 letters (a-z)
    vector = np.zeros(26, dtype=int)
    
    # Count the occurrences of each letter in the string
    letter_counts = Counter(s.lower())  # Convert to lowercase for case insensitivity
    
    # Populate the vector with letter frequencies
    for i in range(26):
        letter = chr(ord('a') + i)
        vector[i] = letter_counts.get(letter, 0)
    
    return vector

def calc_similarity(s1, s2):
    # Construct letter frequency vectors v1 and v2 for s1 and s2
    v1 = construct_letter_frequency_vector(s1)
    v2 = construct_letter_frequency_vector(s2)

    # Calculate the cosine similarity using the formula
    dot_product = np.dot(v1, v2)
    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)

    # Calculate the cosine similarity
    if norm_v1 == 0 or norm_v2 == 0:
        return 0.0  # Handle division by zero
    else:
        similarity = dot_product / (norm_v1 * norm_v2)
        return similarity

# Example usage:
s1 = "abhinav"
s2 = "venkatasatya"
cosine_similarity = calc_similarity(s1, s2)
print(f"Cosine Similarity between '{s1}' and '{s2}': {cosine_similarity:.2f}")

Cosine Similarity between 'abhinav' and 'venkatasatya': 0.65
